@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Mon May 20 14:56:09 +0200 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim decoder_state_machine_behav -key {Behavioral:sim_1:Functional:decoder_state_machine} -tclbatch decoder_state_machine.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/_code/Git/MO8/mo8-digitaal-ontvanger/mo8-digitaal-ontvanger/decoder_behav.wcfg -log simulate.log"
call xsim  decoder_state_machine_behav -key {Behavioral:sim_1:Functional:decoder_state_machine} -tclbatch decoder_state_machine.tcl -protoinst "protoinst_files/design_1.protoinst" -view C:/_code/Git/MO8/mo8-digitaal-ontvanger/mo8-digitaal-ontvanger/decoder_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
